# File: .github/workflows/repo-sync.yml

on:
  push:
    branches: [master]
jobs:
  repo-copy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Copy
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          src_path: ./
          src_branch: roam-research-themes
          dst_path: /backup/roam-research-themes
          dst_owner: palashkaria
          dst_repo_name: actions-playground
