# File: .github/workflows/repo-sync.yml

on:
  schedule:
    - cron: '*/15 * * * *'
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: repo-sync
        uses: repo-sync/github-sync@v2
        with:
          source_repo: 'theianjones/roam-research-themes'
          source_branch: 'master'
          destination_branch: 'theianjones/roam-research-themes'
          github_token: ${{ secrets.GITHUB_TOKEN }}
